const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
const GET_ANNOUNCEMENT_FALURE = "GET_ANNOUNCEMENT_FALURE";

const types = {
  GET_ANNOUNCEMENT,
  GET_ANNOUNCEMENT_SUCCESS,
  GET_ANNOUNCEMENT_FALURE,
};

export default types;
