const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
const GET_ANNOUNCEMENT_FALURE = "GET_ANNOUNCEMENT_FALURE";
const MARK_AS_READ_ANNOUNCEMENT = "MARK_AS_READ_ANNOUNCEMENT";
const types = {
  GET_ANNOUNCEMENT,
  GET_ANNOUNCEMENT_SUCCESS,
  GET_ANNOUNCEMENT_FALURE,
  MARK_AS_READ_ANNOUNCEMENT,
};

export default types;
