const ADD_MARKET = "ADD_MARKET";
const ADD_MARKET_SUCCESS = "ADD_MARKET_SUCCESS";
const ADD_MARKET_FAILURE = "ADD_MARKET_FAILURE";

const GET_MARKET = "GET_MARKET";
const GET_MARKET_SUCCESS = "GET_MARKET_SUCCESS";
const GET_MARKET_FAILURE = "GET_MARKET_FAILURE";

const ADD_CATEGORY = "ADD_CATEGORY";
const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

const GET_CATEGORY = "GET_CATEGORY";
const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

const DELETE_MARKET = "DELETE_MARKET";
const DELETE_MARKET_SUCCESS = "DELETE_MARKET_SUCCESS";
const DELETE_MARKET_FAILURE = "DELETE_MARKET_FAILURE";

const DELETE_CATEGORY = "DELETE_CATEGORY";
const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

const types = {
  ADD_MARKET,
  ADD_MARKET_FAILURE,
  ADD_MARKET_SUCCESS,
  GET_MARKET,
  GET_MARKET_SUCCESS,
  GET_MARKET_FAILURE,
  ADD_CATEGORY,
  ADD_CATEGORY_SUCCESS,
  ADD_CATEGORY_FAILURE,
  GET_CATEGORY,
  GET_CATEGORY_SUCCESS,
  GET_CATEGORY_FAILURE,
  DELETE_CATEGORY,
  DELETE_CATEGORY_SUCCESS,
  DELETE_CATEGORY_FAILURE,
  DELETE_MARKET,
  DELETE_MARKET_SUCCESS,
  DELETE_MARKET_FAILURE,
};
export default types;
