const SIGNIN = "SIGNIN";
const AUTHENTICATED = "AUTHENTICATED";
const SIGNIN_FAILED = "SIGNIN_FAILED";
const SIGNOUT = "SIGNOUT";
const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
const SIGNUP = "SIGNUP";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const CHANGE_PASSWORD = "CHANGE_PASSWORD";
const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

const EDIT_USER = "EDIT_USER";
const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

export default {
  SIGNIN,
  AUTHENTICATED,
  SIGNIN_FAILED,
  SIGNOUT,
  SIGNOUT_SUCCESS,
  SIGNUP,
  SIGNUP_SUCCESS,
  CHANGE_PASSWORD,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_FAILURE,
  EDIT_USER,
  EDIT_USER_SUCCESS,
  EDIT_USER_FAILURE,
};
