const SIGNIN = "SIGNIN";
const AUTHENTICATED = "AUTHENTICATED";
const SIGNIN_FAILED = "SIGNIN_FAILED";
const SIGNOUT = "SIGNOUT";
const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
const SIGNUP = "SIGNUP";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAILED = "SIGNUP_FAILED";
const CHANGE_PASSWORD = "CHANGE_PASSWORD";
const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

const EDIT_USER = "EDIT_USER";
const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

const EDIT_USER_AVATAR = "EDIT_USER_AVATAR";
const EDIT_USER_AVATAR_SUCCESS = "EDIT_USER_AVATAR_SUCCESS";
const EDIT_USER_AVATAR_FAILURE = "EDIT_USER_AVATAR_FAILURE";

const SET_INITIAL_VALUES = "SET_INITIAL_VALUES";
const LOGOUT = "LOGOUT";

const types = {
  SIGNIN,
  AUTHENTICATED,
  SIGNIN_FAILED,
  SIGNOUT,
  SIGNOUT_SUCCESS,
  SIGNUP,
  SIGNUP_SUCCESS,
  CHANGE_PASSWORD,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_FAILURE,
  EDIT_USER,
  EDIT_USER_SUCCESS,
  EDIT_USER_FAILURE,
  SIGNUP_FAILED,
  SET_INITIAL_VALUES,
  EDIT_USER_AVATAR,
  EDIT_USER_AVATAR_FAILURE,
  EDIT_USER_AVATAR_SUCCESS,
  LOGOUT,
};
export default types;
