const GET_ORDERS = "GET_ORDERS";
const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

const NEW_ORDER = "NEW_ORDER";
const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
const NEW_ORDER_FAILURE = "NEW_ORDER_FAILURE";

const types = {
  GET_ORDERS,
  GET_ORDERS_FAILURE,
  GET_ORDERS_SUCCESS,
  NEW_ORDER,
  NEW_ORDER_SUCCESS,
  NEW_ORDER_FAILURE,
};

export default types;
