const GET_ORDERS = "GET_ORDERS";
const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

const NEW_ORDER = "NEW_ORDER";
const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
const NEW_ORDER_FAILURE = "NEW_ORDER_FAILURE";

const SEARCH_ORDER_BY_CUSTOMER_EMAIL = "SEARCH_ORDER_BY_CUSTOMER_EMAIL";
const SEARCH_ORDER_BY_ID = "SEARCH_ORDER_BY_ID";
const SEARCH_ORDER_BY_PRODUCT_ID = "SEARCH_ORDER_BY_PRODUCT_ID";

const VIEW_ORDER = "VIEW_ORDER";
const VIEW_ORDER_SUCCESS = "VIEW_ORDER_SUCCESS";
const VIEW_ORDER_FAILURE = "VIEW_ORDER_FAILURE";

const EDIT_ORDER = "EDIT_ORDER";
const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
const EDIT_ORDER_FAILURE = "EDIT_ORDER_FAILURE";

const EXPORT_TO_EXCEL = "EXPORT_TO_EXCEL";
const EXPORT_TO_EXCEL_SUCCESS = "EXPORT_TO_EXCEL_SUCCESS";
const EXPORT_TO_EXCEL_FAILURE = "EXPORT_TO_EXCEL_FAILURE";

const EDIT_ORDER_PIC = "EDIT_ORDER_PIC";
const EDIT_ORDER_PIC_SUCCESS = "EDIT_ORDER_PIC_SUCCESS";
const EDIT_ORDER_PIC_FAILURE = "EDIT_ORDER_PIC_FAILURE";

const RESET_VARIABLES = "RESET_VARIABLES";

const types = {
  GET_ORDERS,
  GET_ORDERS_FAILURE,
  GET_ORDERS_SUCCESS,
  NEW_ORDER,
  NEW_ORDER_SUCCESS,
  NEW_ORDER_FAILURE,
  SEARCH_ORDER_BY_CUSTOMER_EMAIL,
  SEARCH_ORDER_BY_ID,
  SEARCH_ORDER_BY_PRODUCT_ID,
  VIEW_ORDER,
  VIEW_ORDER_FAILURE,
  VIEW_ORDER_SUCCESS,
  EDIT_ORDER,
  EDIT_ORDER_SUCCESS,
  EDIT_ORDER_FAILURE,
  EXPORT_TO_EXCEL,
  EXPORT_TO_EXCEL_SUCCESS,
  EXPORT_TO_EXCEL_FAILURE,
  EDIT_ORDER_PIC,
  EDIT_ORDER_PIC_SUCCESS,
  EDIT_ORDER_PIC_FAILURE,
  RESET_VARIABLES,
};

export default types;
