const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const FILTER_PRODUCTS_SUCCESS = "FILTER_PRODUCTS_SUCCESS";
const FILTER_PRODUCTS_FAILURE = "FILTER_PRODUCTS_FAILURE";

const ADD_PRODUCT = "ADD_PRODUCT";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

const EDIT_PRODUCT = "EDIT_PRODUCT";
const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

const EDIT_PRODUCT_IMAGE = "EDIT_PRODUCT_IMAGE";
const EDIT_PRODUCT_IMAGE_SUCCESS = "EDIT_PRODUCT_IMAGE_SUCCESS";
const EDIT_PRODUCT_IMAGE_FAILURE = "EDIT_PRODUCT_IMAGE_FAILURE";

const VIEW_PRODUCT = "VIEW_PRODUCT";
const VIEW_PRODUCT_SUCCESS = "VIEW_PRODUCT_SUCCESS";
const VIEW_PRODUCT_FAILURE = "VIEW_PRODUCT_FAILURE";

const types = {
  GET_PRODUCTS,
  GET_PRODUCTS_FAILURE,
  GET_PRODUCTS_SUCCESS,
  FILTER_PRODUCTS,
  FILTER_PRODUCTS_SUCCESS,
  FILTER_PRODUCTS_FAILURE,
  ADD_PRODUCT,
  ADD_PRODUCT_FAILURE,
  ADD_PRODUCT_SUCCESS,
  EDIT_PRODUCT,
  EDIT_PRODUCT_SUCCESS,
  EDIT_PRODUCT_FAILURE,
  EDIT_PRODUCT_IMAGE,
  EDIT_PRODUCT_IMAGE_SUCCESS,
  EDIT_PRODUCT_IMAGE_FAILURE,
  VIEW_PRODUCT,
  VIEW_PRODUCT_SUCCESS,
  VIEW_PRODUCT_FAILURE,
};
export default types;
