const RESERVE_PRODUCT = "RESERVE_PRODUCT";
const RESERVE_PRODUCT_SUCCESS = "RESERVE_PRODUCT_SUCCESS";
const RESERVE_PRODUCT_FAILURE = "RESERVE_PRODUCT_FAILURE";

const GET_RESERVED_PRODUCTS_PM = "GET_RESERVED_PRODUCTS_PM";
const GET_RESERVED_PRODUCTS_FAILURE_PM = "GET_RESERVED_PRODUCTS_FAILURE_PM";
const GET_RESERVED_PRODUCTS_SUCCESS_PM = "GET_RESERVED_PRODUCTS_SUCCESS_PM";

const RELEASE_PRODUCT = "RELEASE_PRODUCT";
const RELEASE_PRODUCT_SUCCESS = "RELEASE_PRODUCT_SUCCESS";
const RELEASE_PRODUCT_FAILURE = "RELEASE_PRODUCT_FAILURE";

const GET_RESERVED_PRODUCTS_PMM = "GET_RESERVED_PRODUCTS_PMM";
const GET_RESERVED_PRODUCTS_FAILURE_PMM = "GET_RESERVED_PRODUCTS_FAILURE_PMM";
const GET_RESERVED_PRODUCTS_SUCCESS_PMM = "GET_RESERVED_PRODUCTS_SUCCESS_PMM";

const types = {
  RESERVE_PRODUCT,
  RESERVE_PRODUCT_SUCCESS,
  RESERVE_PRODUCT_FAILURE,
  GET_RESERVED_PRODUCTS_PM,
  GET_RESERVED_PRODUCTS_SUCCESS_PM,
  GET_RESERVED_PRODUCTS_FAILURE_PM,
  GET_RESERVED_PRODUCTS_PMM,
  GET_RESERVED_PRODUCTS_SUCCESS_PMM,
  GET_RESERVED_PRODUCTS_FAILURE_PMM,
  RELEASE_PRODUCT,
  RELEASE_PRODUCT_SUCCESS,
  RELEASE_PRODUCT_FAILURE,
};

export default types;
